compatibility_date = "2022-01-30"

kv_namespaces = [
  {binding = "VIDEO_KV", id = "e05e87277e004ffe88349adc9eb939ca"},
  {binding = "WEBHOOKS_KV", id = "0805f5afc23746ac838aa399864b6ce0"},
  {binding = "CACHE_KV", id = "d7bc6e6ec2244a44bc0da1ff6173866f"},
  {binding = "IMAGE_KV", id = "39a6bfc25aee40dcbf591588cc43683e"},
]

[durable_objects]
bindings = [
  {name = "USER_DO", class_name = "User", script_name = "user-do"},
  {name = "SETTINGS_DO", class_name = "Settings", script_name = "jkot"},
]

# [secrets]
# STREAM_WEBHOOK_SECRET
# STREAM_ACCOUNT_ID
# STREAM_API_TOKEN
# AUTH0_WEBHOOK_SECRET
